jwt: Java client usage of JWTs
WIP:
- this very barely plumbs JWTs into the Java-side negotiation
- it doesn't correctly authenticate using plumbed JWTs, as seen by the
  test failure when only supplying a JWT and requiring authentication:

org.apache.kudu.test.TestMiniKuduCluster > testJwt FAILED
    org.apache.kudu.client.NonRecoverableException: Couldn't find a valid master in (127.94.224.62:42399). Exceptions received: [org.apache.kudu.client.NonRecoverableException: client requires authentication, but server does not have Kerberos enabled]

The end goal of this patch series is to have a Nifi client fetch a JWT
from an endpoint, and use that to authenticate with a Kudu cluster that
is unable to use Kerberos.

Change-Id: Id02dcd7ee57a838f4763500e78053e21aac21c09